apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    # applicationsSync: create-update
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - prefix: prefix-test
                  folderName: delete-test
                  projectName: default
          - git:
              repoURL: https://github.com/ash-shepard/argo-tests.git
              revision: main
              files:
                - path: "delete-test"

  template:
    metadata:
      name: "test-name-2-electric-boogaloo"

    spec:
      project: "{{projectName}}"
      source:
        repoURL: https://github.com/ash-shepard/argo-tests.git
        targetRevision: main
        path: "{{path}}"
      syncPolicy:
        automated:
          #     prune: true
          selfHeal: true
      #     allowEmpty: true
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
