apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-addons
  namespace: argocd
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:
                - prefix: prefix-test
                  folderName: app-test
                  projectName: default
                - prefix: prefix-test
                  folderName: app-test-2
                  projectName: default
          - git:
              repoURL: https://github.com/ash-shepard/argo-tests.git
              revision: main
              files:
                - path: "{{folderName}}"

  template:
    metadata:
      name: "{{folderName}}"
      component: "{{name}}"
      stage: "test"

    spec:
      project: "{{projectName}}"
      source:
        repoURL: https://github.com/ash-shepard/argo-tests.git
        targetRevision: main
        path: "{{path}}"
      # syncPolicy:
      #   retry:
      #     limit: 2
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "default"
