apiVersion: apps/v1
kind: Deployment
metadata:
  name: blah
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: blah
  template:
    metadata:
      labels:
        app: blah
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          name: blah
          ports:
            - containerPort: 80


